products:
  godel-sls-diagnostics-generator:
    build:
      main-pkg: .
      version-var: github.palantir.build/devx/template-go-cli/cmd.Version
      os-archs:
      - os: darwin
        arch: amd64
      - os: linux
        arch: amd64
    dist:
      disters:
        os-arch-bin:
          type: os-arch-bin
          config:
            os-archs:
            - os: darwin
              arch: amd64
            - os: linux
              arch: amd64
    publish: {}
product-defaults:
  publish:
    group-id: com.palantir.godel-sls-diagnostics-generator
